version: "3"
services:
  php-apache-environment:
    container_name: user-php-apache
    restart: always
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8080:80
    networks:
      - networkName

  db:
    container_name: user-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
    ports:
      - 3306:3306
    networks:
      - networkName

  phpmyadmin:
    container_name: user-myadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - networkName

  adminer:
    container_name: user-adminer
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8888:8080
    networks:
      - networkName

networks:
  networkName:
